### ISSUE TITLE
RayCast 쟁점

### ISSUE THREAD

**Issue by pasongsj** [BeNew98/DirectX_3D#147]
## 목적
> RayCast  시작 위치와 방향에 대한 해결책
## 작업 상세 내용
- [ ] 상황1 - [시작위치 : Player위치 - float4{0.0f, 1000.0f, 0.0f}, 방향 : float4::UP, 거리 : 2000.0 f] 이 경우 가장 아래있는 vertex를 인식함 
->falling state 에서 바닥을 정확하게 체크하지 못함
- [x] 상황2 - [시작위치 : Player위치 - float4{0.0f, 2.0f, 0.0f}, 방향 : float4::DOWN, 거리 : 2000.0f] 이 때 일반적인 Move는 상관이 없지만 falling 시 플레이어의 vertex를 raycasting한 결과가 나옴 시작위치의 y값을 50.0f이상으로 바꾼 경우 플랫폼을 인식하지 못하고 바닥을 인식해 똑같이 falling상태
## 참고 사항
![스크린샷 2023-09-26 125517](https://github.com/BeNew98/DirectX_3D/assets/43164999/61e2433d-f594-46ea-be89-c4ca19db64c9)
![스크린샷 2023-09-26 131005](https://github.com/BeNew98/DirectX_3D/assets/43164999/4f67d834-d38a-4eba-bcb4-b993cb9cb4b3)

요약
플레이어 -2.0f에 down은 falling 시 플레이어 인식해서 문제
플레이어 -1000에 up 은 플랫폼이 아닌 아래바닥 인식해서 문제
+) raycast를 이용하여 계단을 내려올 때 
```
		m_pCapsuleComp->GetDynamic()->setLinearVelocity({ 0,0,0 });
		m_pCapsuleComp->SetMoveSpeed(float4::ZERO);
```
이게 적용되지 않도록 조건문을 추가했지만 떨어지는 느낌이 남아있음

**Comment by BeNew98** [comment]
계단문제는 그거 떄문에 지금 cct완성중임
캡슐 컴포넌트가 아니라 CCT컴포넌트를 쓰면 문제가 아예 사라진대서 거의 다만들었음
문제는 이미 캡슐로 쓴거 전부 바꿔야하는문제 때문에 지금 함수 이름 동일화 진행중임

대충 바꿔서 PhysX 브랜치에서 테스트를 해봤는데  오르락내리락이 깔끔하긴함

**Comment by pasongsj** [comment]
둘 중 하나만 해결되면 되므로 해결~
