### ISSUE TITLE
StartEventAnimation

### ISSUE THREAD

**Issue by BeNew98** [BeNew98/DirectX_3D#156]
## 목적
> 애니메이션이 시작될떄 시전되는 콜백함수 만들기
## 작업 상세 내용
- [x] setFuntion추가
- [x] 해당 프레임에 동작하게 update에 추가
## 참고 사항
근데 이게 최초 한번인건지 아니면 다음 시간에 해당 프레임이 같으면 다시 시전해야하는것인지?
혹은 그것도 세팅이 가능해야 하는것?

이거 2d때도 샘이 말했던거같은 기시감이 든다

**Comment by BeNew98** [comment]
SetAnimationStartFunc 함수 추가완료
update중 해당 프레임에 동작 확인

**Comment by BeNew98** [comment]
제작 해보니까 한번만 하는게 맞는거같아서 일단 그렇게 수정

근데 프레임이 겁나 낮아서 그런지 해당 프레임이 씹혀서 넘어가는 경우 동작을 안하는듯?

**Comment by pasongsj** [comment]
1. 씹히는 문제 해결
2. GameEngineFBXRenderer.cpp 84~87 
```
if (true == Loop)
{
	CurFrame = Start;	
}
``` 
여기로 옮겨야 하는데 실수로 loop가 아닌 경우로 옮김 추가 업데이트 부탁
